### ISSUE TITLE
MacOS 上app build 并 安装后 打开时 报错

### ISSUE THREAD

**Issue by harryhare** [tabris17/doufen#13]
点击程序图标后，报错如下：
```
Uncaught Exception:
Error: spawn service ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:685:11)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```
另外，linux的那个issue，macos 上也会出现。

**Comment by tabris17** [comment]
MacOS上app只能用npm run app 启动，因为启动service的代码没有做兼容处理。
找不到service这个可执行文件。
见：https://github.com/tabris17/doufen/blob/a3d13bb282926dcf50c732a11a58e59fadd94b61/src/app/main.js#L116
