### ISSUE TITLE
MacOS server build 报错

### ISSUE THREAD

**Issue by harryhare** [tabris17/doufen#14]
执行 npm run build:service 后
```
> doufen-platform@0.1.0 build:service /Users/xxx/git/doufen
> source .venv/bin/activate && source ./scripts/build.sh

268 INFO: PyInstaller: 3.3.1
268 INFO: Python: 3.6.5
279 INFO: Platform: Darwin-16.7.0-x86_64-i386-64bit
280 INFO: wrote /Users/xxx/git/doufen/service.spec
283 INFO: UPX is not available.
285 INFO: Extending PYTHONPATH with paths
['/Users/xxx/git/doufen/src/service', '/Users/xxx/git/doufen']
286 INFO: checking Analysis
297 INFO: Appending 'binaries' from .spec
297 INFO: Appending 'datas' from .spec
304 INFO: checking PYZ
310 INFO: checking PKG
310 INFO: Building PKG because out00-PKG.toc is non existent
310 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "/Users/xxx/git/doufen/.venv/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/api.py", line 411, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/api.py", line 196, in __init__
    self.__postinit__()
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/api.py", line 259, in assemble
    dist_nm=inm)
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/building/utils.py", line 207, in checkCache
    dylib.mac_set_relative_dylib_deps(cachedfile, dist_nm)
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/PyInstaller/depend/dylib.py", line 308, in mac_set_relative_dylib_deps
    dll = MachO(libname)
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/macholib/MachO.py", line 95, in __init__
    self.load(fp)
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/macholib/MachO.py", line 110, in load
    self.load_header(fh, 0, size)
  File "/Users/xxx/git/doufen/.venv/lib/python3.6/site-packages/macholib/MachO.py", line 147, in load_header
    header, fh))
ValueError: Unknown Mach-O header: 0x89504e47 in <_io.BufferedReader name='/Users/xxx/Library/Application Support/pyinstaller/bincache00_py36_64bit/static/logo.png'>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doufen-platform@0.1.0 build:service: `source .venv/bin/activate && source ./scripts/build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doufen-platform@0.1.0 build:service script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by tabris17** [comment]
这个问题我以为已经修复了。不过没有在MacOS上测试过。

**Comment by harryhare** [comment]
pull了一下，build 正常了。。。

**Comment by tabris17** [comment]
╮(￣▽￣"")╭
