### ISSUE TITLE
Ubuntu上启动失败

### ISSUE THREAD

**Issue by djndl1** [tabris17/doufen#3]
Ubuntu 14.04 运行`npm run app`和`npm run service`，按任意键继续之后弹出如下错误

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /home/djn_dl/桌面/doufen/src/app/app.ico
    at createTray (/home/djn_dl/桌面/doufen/src/app/window.js:133:16)
    at BrowserWindow.splash.once (/home/djn_dl/桌面/doufen/src/app/main.js:179:21)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at BrowserWindow.emit (events.js:210:7)
    at EventEmitter.<anonymous> (/home/djn_dl/桌面/doufen/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:478:12)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (/home/djn_dl/桌面/doufen/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:275:13)
    at emitTwo (events.js:125:13)
```

**Comment by tabris17** [comment]
好像是图标文件格式错误导致的，你试试把app.ico用别的图标替换试试

**Comment by tabris17** [comment]
我找到原因了，https://github.com/electron/electron/blob/b09086c1b8a498c8d5184c6cb466dd3b1a668094/docs/api/native-image.md#supported-formats

好像是Linux的Tray不支持ICO格式
